//! Jeton d'authentification du serveur local.
//!
//! Genere a chaque demarrage et depose dans le dossier de donnees, il permet
//! aux clients legitimes de prouver qu'ils ont acces a ce dossier.
//!
//! Portee reelle : ce jeton empeche un programme qui ignore son existence de
//! piloter le serveur. Il n'arrete pas un programme malveillant tournant sous
//! le meme compte, qui peut simplement lire le fichier. La vraie frontiere
//! reste un serveur distant que l'utilisateur ne controle pas.

use std::fs;
use std::sync::RwLock;
use uuid::Uuid;

use crate::storage;

lazy_static::lazy_static! {
    static ref CURRENT: RwLock<Option<String>> = RwLock::new(None);
}

/// Mode strict : refuse les connexions WebSocket sans jeton valide.
/// Active par defaut. Escape hatch : `CRIMSON_STRICT_AUTH=0` (ou `false`/`off`)
/// pour accepter temporairement les clients non authentifies.
pub fn strict_mode() -> bool {
    match std::env::var("CRIMSON_STRICT_AUTH") {
        Ok(v) => {
            let v = v.trim().to_ascii_lowercase();
            !(v == "0" || v == "false" || v == "off" || v == "no")
        }
        Err(_) => true,
    }
}

pub fn generate_and_save_token() -> String {
    let token = Uuid::new_v4().to_string();
    let data_dir = storage::get_data_dir();
    let token_path = data_dir.join("auth.token");

    if let Err(e) = fs::write(&token_path, &token) {
        tracing::error!("Failed to write auth.token: {}", e);
    } else {
        tracing::info!("Auth token generated and saved to {:?}", token_path);
    }

    if let Ok(mut cur) = CURRENT.write() {
        *cur = Some(token.clone());
    }

    // StreamDock HTML plugins often cannot read %APPDATA% via require/ActiveX.
    // Mirror the token beside each installed plugin so a <script> include works,
    // and keep /local/ws-token as the primary runtime fallback.
    publish_token_to_streamdock_plugins(&token);

    token
}

/// Write `window.__CRIMSON_AUTH_TOKEN__ = '…'` into known StreamDock plugin dirs.
fn publish_token_to_streamdock_plugins(token: &str) {
    let appdata = match std::env::var("APPDATA") {
        Ok(v) if !v.is_empty() => v,
        _ => return,
    };
    let plugins_base = std::path::Path::new(&appdata)
        .join("HotSpot")
        .join("StreamDock")
        .join("plugins");
    // Escape for a single-quoted JS string (UUID has neither quote nor backslash).
    let safe = token.replace('\\', "\\\\").replace('\'', "\\'");
    let js = format!(
        "/* generated by crimson-server — do not edit */\nwindow.__CRIMSON_AUTH_TOKEN__ = '{}';\n",
        safe
    );
    let plugin_ids = [
        "com.laoy.streamdock.spotify.sdPlugin",
        "com.laoy.streamdock.crimson.sdPlugin",
        "com.laoy.streamdock.discord.sdPlugin",
    ];
    for id in plugin_ids {
        // Spotify/Crimsons load scripts from plugin/; Discord index.html is at plugin root.
        for rel in ["plugin/crimson_auth_token.js", "crimson_auth_token.js"] {
            let path = plugins_base.join(id).join(rel);
            if let Some(parent) = path.parent() {
                if !parent.exists() {
                    continue;
                }
                if let Err(e) = fs::write(&path, &js) {
                    tracing::warn!("Failed to publish auth token helper to {:?}: {}", path, e);
                }
            }
        }
    }
}

pub fn read_token() -> Option<String> {
    let data_dir = storage::get_data_dir();
    let token_path = data_dir.join("auth.token");
    fs::read_to_string(token_path).ok().map(|s| s.trim().to_string())
}

/// Jeton de la session en cours, sans relire le disque a chaque connexion.
pub fn current_token() -> Option<String> {
    if let Ok(cur) = CURRENT.read() {
        if let Some(t) = cur.as_ref() {
            return Some(t.clone());
        }
    }
    read_token()
}

/// Compare en temps constant, pour ne pas laisser deviner le jeton octet par
/// octet a partir du temps de reponse.
pub fn verify(candidate: &str) -> bool {
    let expected = match current_token() {
        Some(t) if !t.is_empty() => t,
        _ => return false,
    };
    if candidate.len() != expected.len() {
        return false;
    }
    let diff = candidate
        .bytes()
        .zip(expected.bytes())
        .fold(0u8, |acc, (a, b)| acc | (a ^ b));
    diff == 0
}
